---

- name: Ensure elasticsearch is started
  service: name={{instance_init_script | basename}} state=started enabled=yes

- name: Wait for elasticsearch to startup
  wait_for: host={{es_api_host}} port={{es_api_port}} delay=10

- name: Get template files
  find: paths="/etc/elasticsearch/templates" patterns="*.json"
  register: templates

- name: Install templates without auth
  uri:
    url: "http://{{es_api_host}}:{{es_api_port}}/_template/{{item.path | filename}}"
    method: PUT
    status_code: 200
    body_format: json
    body: "{{ lookup('file', item.path) }}"
  when: not es_enable_xpack or not es_xpack_features is defined or "security" not in es_xpack_features
  with_items: "{{ templates.files }}"

- name: Install templates with auth
  uri:
    url: "http://{{es_api_host}}:{{es_api_port}}/_template/{{item.path | filename}}"
    method: PUT
    status_code: 200
    user: "{{es_api_basic_auth_username}}"
    password: "{{es_api_basic_auth_password}}"
    force_basic_auth: yes
    body_format: json
    body: "{{ lookup('file', item.path) }}"
  when: es_enable_xpack and es_xpack_features is defined and "security" in es_xpack_features
  with_items: "{{ templates.files }}"
