"""Add uploader_ip column to torrents table.

Revision ID: 3001f79b7722
Revises: 
Create Date: 2017-05-21 18:01:35.472717

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '3001f79b7722'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('nyaa_torrents', sa.Column('uploader_ip', sa.Binary(), nullable=True))
    op.add_column('sukebei_torrents', sa.Column('uploader_ip', sa.Binary(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('nyaa_torrents', 'uploader_ip')
    op.drop_column('sukebei_torrents', 'uploader_ip')
    # ### end Alembic commands ###
