"""Added range bans

Revision ID: b02a99465710
Revises: 6cc823948c5a
Create Date: 2018-04-16 15:20:31.923251

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'b02a99465710'
down_revision = '6cc823948c5a'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('rangebans',
    sa.Column('_cidr_string', sa.String(length=18), nullable=False),
    sa.Column('masked_cidr', sa.BigInteger(), nullable=False),
    sa.Column('mask', sa.BigInteger(), nullable=False),
    sa.Column('enabled', sa.Boolean(), nullable=False),
    sa.Column('temporary_tor', sa.Boolean(), nullable=False),
    sa.PrimaryKeyConstraint('masked_cidr')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('rangebans')
    # ### end Alembic commands ###
