"""Added notifications option

Revision ID: dff52e057cbf
Revises: 306b45f72b8c
Create Date: 2017-09-19 11:52:13.594118

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = 'dff52e057cbf'
down_revision = '306b45f72b8c'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('nyaa_torrents', sa.Column('notifications', sa.Boolean(), nullable=False))
    op.add_column('sukebei_torrents', sa.Column('notifications', sa.Boolean(), nullable=False))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('sukebei_torrents', 'notifications')
    op.drop_column('nyaa_torrents', 'notifications')
    # ### end Alembic commands ###
