---

server.name: kibana
server.host: '0.0.0.0'
server.basePath: /kibana
server.rewriteBasePath: true
# server.defaultRoute: /kibana/app/kibana
elasticsearch.url: http://elasticsearch:9200
xpack.monitoring.ui.container.elasticsearch.enabled: true
