---

- name: Include optional user and group creation.
  when: (es_user_id is defined) and (es_group_id is defined)
  include: elasticsearch-optional-user.yml

- name: Include specific Elasticsearch
  include: elasticsearch-Debian.yml
  when: ansible_os_family == 'Debian'
